### ISSUE TITLE
Word use timeline

### ISSUE THREAD

**Issue by Zimbardoex** [drozado/NYT-Media-Analytics#10]
As a user of the site, I want to see a graph of a word use over time.

#### Sub tasks:
* [x] #14 Creating model functions to read and access models
* [x] #6 API route for frequency over time
* [x] #8 Create a line graph for timeline
